version: '3'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    container_name: DBPostgresTeslo
    volumes:
      - ./postgres:/var/lib/postgresql/data 